image: maven:3-jdk-8
build:
  script: "mvn clean package install javadoc:javadoc"
  artifacts:
    name: "SkycadeKitPVP"
    paths:
    - "target/*.jar"
cache:
  paths:
    - .m2/
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"