image: maven:3-jdk-8
build:
  script:
  - mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=dependencies/SkycadeCore-1.48.3-SNAPSHOT.jar -DgroupId=net.skycade -DartifactId=SkycadeCore -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar
  - mvn clean package install javadoc:javadoc
  artifacts:
    name: "SkycadeKitPVP"
    paths:
    - "target/*.jar"
cache:
  paths:
    - .m2/
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"