name: KitPvP
main: net.skycade.kitpvp.KitPvP
version: 3.4.1-SNAPSHOT
author: ["WhiteWalker72", "Riccardo Bello (RickyB98)"]
depend: [SkycadeCore]
commands:
    givekey:
    keys:
    givekeys:
    unlock:
    unlockkit:
    lock:
    lockkit:
permission:
  kitpvp.nametag.view:
    default: op