name: KitPvP
main: net.skycade.kitpvp.KitPvP
version: 4.0.0-SNAPSHOT
author: ["WhiteWalker72", "Riccardo Bello (RickyB98)", "Taon2"]
depend: [SkycadeCore]
commands:
    givekey:
    keys:
    givekeys:
    unlock:
    unlockkit:
    lock:
    lockkit:
permission:
  kitpvp.nametag.view:
    default: op