name: KitPvP
main: net.skycade.kitpvp.KitPvP
version: 4.0.1-SNAPSHOT
authors: ["WhiteWalker72", "Riccardo Bello (RickyB98)", "Taon2"]
depend: [SkycadeCore, GuardianBeamAPI]
softdepend: [SkycadeLeaderboards, GangsPlus, SkycadeKoth, SkycadeCrates]
commands:
permission:
  kitpvp.nametag.view:
    default: op