name: KitPvP
main: net.skycade.kitpvp.KitPvP
version: 3.0.6-SNAPSHOT
author: ["WhiteWalker72", "Riccardo Bello (RickyB98)"]
depend: [SkycadeCore]
commands:
    givekey:
    keys:
    givekeys:
    unlock:
    unlockkit:
    lock:
    lockkit: